export const initialTags = [
    "Full-Stack Developer",
    "Front-End Developer",
    "Back-End Developer",
    "Data Scientist",
    "UI/UX Designer",
    "Graphic Designer",
    "Mobile Developer",
    "Cloud Engineer",
    "SoftwareEngineer",
    "Game Developer",
    "web Developer",
    "Hr Manager",
    "Financial Analysist",
    "Teacher",
    "Healthcare Professional",
    "Legal Counsel",
    "Sales Representative",
    "Marketing Designer"
];